version: '3'
services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile-api
    ports:
      - 5000:5000
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    container_name: db
    image: mysql
    ports:
      - 3306:3306
    expose:
      # Opens port 3306 on the container
      - '3306'
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    user: mysql # <- user
  redis:
    image: redis:6
  dev:
    container_name: dev
    build:
      dockerfile: Dockerfile-dev
      context: .
    env_file:
      - .env
  docs:
    container_name: docs
    build:
      dockerfile: Dockerfile-docs
      context: ./
    ports:
      - 3001:3001
    env_file:
      - ./.env
  web:
    build:
      context: .
      dockerfile: Dockerfile-web
    image: web
    ports:
      - 3000:3000
    depends_on:
      - api
    env_file: .env
volumes:
  db:
    driver: local