FROM node:16.13.2-alpine AS builder
RUN apk update
# Set working directory
WORKDIR /app
RUN yarn global add turbo

# turbo prune
RUN turbo prune --scope=api --docker

# Add lockfile and package.json's of isolated subworkspace
FROM node:16.13.2-alpine AS installer
# RUN apk update
WORKDIR /app
COPY .gitignore .gitignore
COPY turbo.json turbo.json

# Install dependencies
COPY package.json ./
COPY yarn.lock ./
COPY ./apps/api/package.json ./apps/api/package.json
COPY ./packages/prisma/package.json ./packages/prisma/package.json
RUN yarn install
# RUN yarn turbo run build 

# Copy source files
COPY ./apps/api ./apps/api
COPY ./packages ./packages

FROM node:16.13.2-alpine AS runner
WORKDIR /app

# Don't run production as root
RUN addgroup --system --gid 1001 expressjs
RUN adduser --system --uid 1001 expressjs
USER expressjs
COPY --from=installer /app .

# EXPOSE 5000
CMD ["node", "-e", "(function() { setInterval(() => { console.log(\"hello\") }, 5000) })()"]