import React, { ReactChild } from "react";
import { Flex, Box } from "@chakra-ui/react";
import { Navbar } from "ui";
import Head from "next/head";

type LayoutProps = {
  children: ReactChild | ReactChild[];
};

export default function Layout({ children }: LayoutProps) {
  return (
    <>
      <Head>
        <title>Inspirers</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Flex
        width="100%"
        height="100%"
        minHeight="100vh"
        direction="column"
        margin={0}
      >

        <Flex width="100%" height="100%">
          <Box bg="#333333" p="8" height="100vh" color="#fff">
            <ul>
              <li>Journeys</li>
              <li>Notifications</li>
              <li>Tasks</li>
              <li>Communitis</li>
              <li>Analytics</li>
              <li>Discover</li>
              <li>Settings</li>
            </ul>
          </Box>
          <Box p="8">
          <Navbar />
          {children}
          </Box>
        </Flex>
      </Flex>
    </>
  );
}
