import React, { ReactChild } from "react";
import { Flex, Box } from "@chakra-ui/react";
import { Navbar } from "ui";
import Link from "next/link";
import Head from "next/head";

type LayoutProps = {
    children: ReactChild | ReactChild[];
};

export default function NestedLayout({ children }: LayoutProps) {
    return (
        <>
            <Head>
                <title>Inspirers</title>
                <meta name="description" content="Generated by create next app" />
            </Head>
            <Flex height="100vh" >
                <Box bg="#2C3639" p="8" width="10%" height="100%" color="#fff" boxShadow="rgba(0, 0, 0, 0.08) 0px 4px 12px">
                    <Box as="aside">
                        <ul>
                            <li><Link href="/">Home</Link></li>
                            <li><Link href="/journeys">Journeys</Link></li>
                            <li><Link href="/profile">Profile</Link></li>
                            <li><Link href="/notifications">Notifications</Link></li>
                            <li><Link href="/tasks">Tasks</Link></li>
                            <li><Link href="/communitis">Communitis</Link></li>
                            <li><Link href="/discover">Discover</Link></li>
                            <li><Link href="/settings">Settings</Link></li>
                        </ul>
                    </Box>
                </Box>
                <Box width="90%" height="100%">
                    <Navbar />
                    {children}
                </Box>
            </Flex>
        </>
    );
}
